# Generated by Django 3.2.8 on 2021-10-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.CharField(max_length=250)),
                ('gear', models.CharField(max_length=250)),
                ('geartype', models.CharField(max_length=250)),
                ('brake', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='uploads')),
            ],
        ),
    ]
