# Generated by Django 3.2.8 on 2021-10-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('css', models.TextField()),
                ('html', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='cycles',
            name='image',
            field=models.ImageField(upload_to='media/uploads'),
        ),
    ]
