# Generated by Django 3.2.8 on 2021-10-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycleapp', '0002_auto_20211016_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('logo', models.ImageField(upload_to='media/logo')),
            ],
        ),
        migrations.DeleteModel(
            name='Cycles',
        ),
    ]
