# Generated by Django 3.2.8 on 2021-10-16 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycleapp', '0003_auto_20211016_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=250)),
                ('frame', models.CharField(max_length=250)),
                ('fork', models.CharField(max_length=250)),
                ('derailleur', models.CharField(max_length=250)),
                ('brake', models.CharField(max_length=250)),
                ('gear', models.CharField(max_length=250)),
                ('wight_in_kg', models.CharField(max_length=250)),
                ('price_in_inr', models.IntegerField()),
                ('image', models.ImageField(upload_to='media/uploads')),
                ('image_url', models.CharField(max_length=250)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycleapp.company')),
            ],
        ),
    ]
