# Generated by Django 3.2.8 on 2021-10-16 06:06

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycleapp', '0004_cycles'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycles',
            name='model_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
