# Generated by Django 3.2.8 on 2021-10-19 15:13

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycleapp', '0006_auto_20211016_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycles',
            name='brake',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cycles',
            name='derailleur',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cycles',
            name='fork',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cycles',
            name='frame',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cycles',
            name='frame_desc',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cycles',
            name='gear',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cycles',
            name='gear_desc',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cycles',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cycles',
            name='model',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cycles',
            name='model_color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='cycles',
            name='price_in_inr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cycles',
            name='tyre_desc',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cycles',
            name='wight_in_kg',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
