# Generated by Django 3.2.8 on 2021-10-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycleapp', '0007_auto_20211019_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='', verbose_name='media/home')),
            ],
        ),
    ]
